contentType: User
title: Matt Wheal -X (mwheal - ZENSAR TECHNOLOGY (UK) LIMITED at Cisco)
UserName: mwheal
Email: mwheal@cisco.com
Enabled: !!bool true
FirstName: Matt
MiddleName: 
LastName: Wheal
NickName: null
DisplayName: Matt Wheal -X (mwheal - ZENSAR TECHNOLOGY (UK) LIMITED at Cisco)
IsExternalUser: !!bool true
UPN: 
Gender: null
LastLoginDate: 2019-09-26T11:05:26.0000000
CardRequestedLast: 2017-07-11T12:29:47.0000000
OTPSecret: null
Timezone: Europe/London
Locale: en-US
LastOTPCheck: null
UserRolesPart:
  Roles:
    - Authenticated
    - Administrator
    - Red Badge
    - cisco-cards-devs
    - cisco-allmgrs
